# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'BreedUp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BreedUp
#  pod 'Firebase/Core', '~> 5.18.0'
#  pod 'Firebase/Database', '~> 5.18.0'
#  pod 'Firebase/Storage', '~> 5.18.0'
#  pod 'Firebase/Auth', '~> 5.18.0'
#  pod 'Firebase/Firestore', '~> 5.18.0'
#  pod 'Firebase/Messaging'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'

  pod 'RNFBStorage', :path => '../node_modules/@react-native-firebase/storage'

end
